config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'topics#index'
  resources :topics
  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end
  resources :users, only: [:index, :show, :edit, :updates]
  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to topics_path, notice: "コメントを削除しました！"
  end

  def edit
    @comment = Comment.find(params[:id])
    @topic_id =@comment.topic.id
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    if @comment.save
      redirect_to topics_path, notice: "コメントを編集しました！"
    else
      render action: 'new'
    end
  end

  def new
    if params[:back]
      @comment = Comment.new(comments_params)
    else
      @comment = Comment.new
    end
  end


  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    @topic_id = @topic.id
    unless @comment.topic.user_id == current_user.id
      @notification = @comment.notifications.build(user_id: @topic.user.id )
    end

    respond_to do |format|
      if @comment.save
       format.html { redirect_to topics_path, notice: 'コメントを投稿しました。' }
       format.json { render :index, status: :created, location: @comment }
       format.js { render :index }
       unless @comment.topic.user_id == current_user.id
         Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'comment_created', {
            message: 'あなたの投稿にコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
          uncreate_count: Notification.where(user_id: @comment.topic.user.id).count
        })
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, remote: true) do |f| %>
  <%= f.error_messages! %>
  <div class="field">
    <%= f.hidden_field :topic_id, :value => @topic_id  %>
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
     <% if comment.topic_id == id then %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <% if current_user.id == comment.user_id %>
              <%= link_to "編集", edit_comment_path(comment.id), class: 'btn btn-default btn-sm btn-success' %>
              <%= link_to "削除", comment_path(comment.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
            <% end %>
          </p>
        <% end %>
      </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>コメントを編集する</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area_<%= @topic_id %>").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic, id: @topic_id }) %>")
$(':text').val('')