config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'topics#index'
  resources :topics
  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end
  resources :users, only: [:index, :show, :edit, :updates]
  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  mount_uploader :picture, AvatarUploader

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  PERMISSIBLE_ATTRIBUTES = %i(name picture picture_cache)

  def index
    @topics = Topic.all
    @topic = Topic.new
    @comments = Comment.all
    @comment = @topic.comments.build
    @topic_id = ""
    @users = User.all
  end

  def show
    @topic = Topic.find(params[:id])
    @comment = @topic.comments.build
    @comments = @topic.comments
    @topic_id = ""
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
    if params[:notification_id] != nil then
      Notification.find(params[:notification_id]).update(read: true)
    end
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "投稿しました。"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render action: 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(topics_params)
    if @topic.save
      redirect_to topics_path, notice: "投稿を編集しました。"
    else
      render action: 'new'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path, notice: "投稿を削除しました！"
  end

  private
    def topics_params
      params.require(:topic).permit(:content, :picture)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new'
      topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end

  def send_img(topic)
    return image_tag(topic.picture, alt: topic.user.name )
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic, url: choose_new_or_edit) do |f| %>
<%= f.error_messages! %>

  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>
  <br>
  <div class="field">
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div><br>

  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "投稿一覧画面にもどる", topics_path %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>投稿を編集する</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container-fluid">
  <div class="wrapper col-sx-11">
    <p class="flash"><%= notice %><%= alert %></p>

    <div class="row">
      <div class="col-xs-7">
        <h1>投稿一覧</h1>
        <%= link_to "投稿する", new_topic_path, class: 'btn btn-default' %>
        <% @topics.all.includes(:user).reverse.each do |topic| %>
          <% if (current_user.following?(topic.user) && topic.user.following?(current_user)) || topic.user == current_user then %>
            <div class="row topic">
              <p class="icon"><%= profile_img(topic.user) if profile_img(topic.user) %></p>
              <div style="display:inline;">&nbsp;&nbsp;&nbsp;<%= topic.user.name %>さんが <%=topic.updated_at.strftime("%Y-%m-%d %H:%M")%> に投稿しました。</div>
              <p><strong><%= topic.content.truncate(33)%></strong></p>
              <% if topic.picture.url != nil then%>
                <%= send_img(topic) %></br></br>
              <%end%>
              <%= link_to "詳細", topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
              <% if current_user.id == topic.user_id %>
                <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
                <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
              <% end %>
              <HR width="100%">
              <p>コメント一覧</p>
              <% @topic_id = topic.id%>
              <div id="comments_area_<%= topic.id %>">
                <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic, id: @topic_id } %>
              </div>
              <%= render partial: 'comments/form', locals: { comment: @comment, id: @id} %>
            </div>
          <%end%>
        <% end %>
      </div>

      <div class="col-xs-offset-1 col-xs-4 friend">
        <h2>友達</h2>
        <% @users.each do |user| %>
            <div class="container-child">
              <% if user.id != current_user.id && current_user.following?(user) && !(user.following?(current_user)) then%>
                    <div class="item">
                      <p class="icon"><%= profile_img(user) %></p>
                      <%= link_to user.name, user %>
                      <span>(申請中)</span>
                    </div>
              <% end %>
              <% if user.id != current_user.id && current_user.following?(user) && user.following?(current_user) then%>
                    <div class="item">
                      <p class="icon"><%= profile_img(user) %></p>
                      <%= link_to user.name, user %>
                      <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-default btn-sm btn-success'%>
                  </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>投稿記事を作成する</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="wrapper col-sx-11">
    <h2>記事詳細</h2>
    <p id="notice"><%= notice %></p>

      <div class="child row">
        <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
          <div class="topic-text">
            <p class="icon"><%= profile_img(@topic.user) if profile_img(@topic.user) %></p>
            <h5 style="display:inline;">&nbsp;&nbsp;&nbsp;<%= @topic.user.name  %>が投稿しました。</h5>
            <p class="left"><strong>内容</strong></p>
            <p class="left"><%= @topic.content %></p>
            <p class="right">
              <% if current_user.id == @topic.user_id %>
                <%= link_to '編集', edit_topic_path(@topic), class: 'btn btn-default btn-sm btn-success'  %></br>
              <% end %>
              <strong>作成時間:</strong>
              <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
          </div>          
          <p>コメント一覧</p>
          <% @topic_id = @topic.id%>
          <div id="comments_area">
            <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic, id: @topic_id } %>
          </div>
          <%= render partial: 'comments/form', locals: { comment: @comment, id: @topic_id} %>
          </br>
          <%= link_to '戻る', topics_path %>
        </div>
      </div>
  </div>
</div>