config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'topics#index'
  resources :topics
  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end
  resources :users, only: [:index, :show, :edit, :updates]
  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  belongs_to :message
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>お知らせ</h2>
    <div class="row">
    <ul>
      <% @notifications.each do |notification| %>
      <hr>
       <li class = "col-xs-10" >
         <% if notification.comment_id != nil then%>
            <span><%= if notification.read == true then "既読" else "未読" end%></span>
            <p>
              <%= notification.comment.user.try(:name) %>さんが
              あなたの投稿（<%= link_to "#{notification.comment.topic.content}", topic_path(notification.comment.topic, notification_id: notification.id)%>）にコメントしました。
            </p>
            <p><%= notification.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          <% elsif notification.message_id !=nil then%>
            <span><%= if notification.read == true then "既読" else "未読" end%></span>
            <p>
              <%= link_to notification.message.user.try(:name) , conversation_messages_path(notification.message.conversation_id, notification_id: notification.id) %>さんから
              あなたにメッセージがあります。
            </p>
            <p><%= notification.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>