config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'topics#index'
  resources :topics
  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end
  resources :users, only: [:index, :show, :edit, :updates]
  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendPark</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
    <script src="https://js.pusher.com/3.0/pusher.min.js"></script>
    <% if user_signed_in? %>
      <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
          encrypted: true
        });
        var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
        channel.bind('comment_created', function(data) {
          alert(data.message);
        });
        channel.bind('message_created', function(data) {
          alert(data.message);
        });
        channel.bind('notification_created', function(data) {
        $('#unread_count').html(data.unread_count);
        });
    　</script>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "FriendPark", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>\
              <li class="icon"><%= profile_img(current_user) %></li>
              <li><%= link_to current_user.name, user_path(current_user.id) %></li>
              <li><%= link_to "メッセージ", conversations_path %></li>
              <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
              <%= link_to notifications_index_path, class: "navbar-brand" do %>
                <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
              <% end %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path  %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </nav>
    </header>

    <%= yield %>

  </body>
</html>